"""add_unique_constraint_on_external_claim_id

Revision ID: 499eaba7b8ef
Revises: 738f23d3eb94
Create Date: 2025-11-04 09:45:03.203200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '499eaba7b8ef'
down_revision: Union[str, Sequence[str], None] = '738f23d3eb94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.alter_column('claim_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_claims_external_claim_id', ['external_claim_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_constraint('uq_claims_external_claim_id', type_='unique')
        batch_op.alter_column('claim_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)

    # ### end Alembic commands ###
