"""initial migration with claims table

Revision ID: 738f23d3eb94
Revises: 
Create Date: 2025-11-04 08:51:52.403974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '738f23d3eb94'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claims',
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('external_claim_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_npi', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscriber_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan_group_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('net_fee', sa.Numeric(), nullable=False),
    sa.Column('total_provider_fees', sa.Numeric(), nullable=False),
    sa.Column('total_allowed_fees', sa.Numeric(), nullable=False),
    sa.Column('total_member_coinsurance', sa.Numeric(), nullable=False),
    sa.Column('total_member_copay', sa.Numeric(), nullable=False),
    sa.Column('line_count', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('normalized_lines', sa.JSON(), nullable=False),
    sa.Column('claim_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('claim_id')
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index('ix_claims_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_external_claim_id'), ['external_claim_id'], unique=False)
        batch_op.create_index('ix_claims_external_id', ['external_claim_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_claims_provider_npi'), ['provider_npi'], unique=False)
        batch_op.create_index('ix_claims_provider_npi_net_fee', ['provider_npi', 'net_fee'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index('ix_claims_provider_npi_net_fee')
        batch_op.drop_index(batch_op.f('ix_claims_provider_npi'))
        batch_op.drop_index('ix_claims_external_id')
        batch_op.drop_index(batch_op.f('ix_claims_external_claim_id'))
        batch_op.drop_index('ix_claims_created_at')

    op.drop_table('claims')
    # ### end Alembic commands ###
